# Generated by Django 6.0.7 on 2026-07-31 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='कंपनी / बिजनेस का नाम', max_length=150)),
                ('subdomain', models.CharField(db_index=True, help_text='यूनिक सबडोमेन slug (उदा. tata)', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar_position', models.CharField(choices=[('left', 'Left Sidebar'), ('right', 'Right Sidebar'), ('top', 'Top Navbar')], default='left', max_length=10)),
                ('primary_color', models.CharField(default='#4F46E5', max_length=7)),
                ('sidebar_bg_color', models.CharField(default='#1E293B', max_length=7)),
                ('accent_hover_color', models.CharField(default='#6366F1', max_length=7)),
                ('text_color', models.CharField(default='#F8FAFC', max_length=7)),
                ('is_pro_plan', models.BooleanField(default=False)),
                ('custom_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('custom_favicon', models.ImageField(blank=True, null=True, upload_to='branding/favicons/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.tenant')),
            ],
        ),
    ]
