# Generated by Django 6.1 on 2026-09-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantEmailSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(help_text='जैसे: ratan-enterprises', max_length=100, unique=True)),
                ('domain', models.CharField(default='kosisko.com', max_length=100)),
                ('private_key_pem', models.TextField(help_text='PEM format में एन्क्रिप्टेड प्राइवेट की')),
                ('public_key_pem', models.TextField(help_text='PEM format में पब्लिक की')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
