# Generated by Django 6.1 on 2026-09-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantemailsecurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, help_text='कस्टम डोमेन (उदा. portal.clientdomain.com)', max_length=255, null=True, unique=True),
        ),
    ]
