# Generated by Django 6.1 on 2026-09-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_smart_rental', '0003_alter_newdeviceonboardinglead_tenant_and_more'),
        ('marketplace', '0003_alter_tenantappsubscription_tenant'),
        ('pos_billing', '0002_alter_invoice_tenant_alter_product_tenant'),
        ('tenants', '0003_tenant_custom_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantbranding',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='TenantBranding',
        ),
    ]
