# Generated by Django 6.0.7 on 2026-07-31 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='मॉड्यूल कोड (उदा. pos_billing, crm_sales)', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('core', 'Core / Default'), ('sales', 'Sales & POS'), ('inventory', 'Inventory & Warehouse'), ('crm', 'CRM & Marketing'), ('finance', 'Finance & Accounting'), ('hr', 'HR & Payroll'), ('ai', 'AI & Automation')], default='sales', max_length=20)),
                ('short_description', models.CharField(max_length=255)),
                ('icon_class', models.CharField(default='fa-boxes-stacked', help_text='FontAwesome Icon Class', max_length=50)),
                ('is_free', models.BooleanField(default=False)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active_in_store', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantAppSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.businessmodule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_apps', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'module')},
            },
        ),
    ]
