# Generated by Django 6.0.7 on 2026-08-03 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon_class', models.CharField(default='fa-cubes', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='tenantappsubscription',
            old_name='expires_at',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='tenantappsubscription',
            old_name='subscribed_at',
            new_name='purchased_at',
        ),
        migrations.AddField(
            model_name='tenantappsubscription',
            name='data_archive_mode',
            field=models.BooleanField(default=False, help_text='True होने पर डेटा Read-Only रहेगा, मिटेगा नहीं'),
        ),
        migrations.AddField(
            model_name='tenantappsubscription',
            name='last_uninstalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantappsubscription',
            name='remaining_active_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tenantappsubscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active & Installed'), ('PAUSED_UNINSTALLED', 'Uninstalled (Prorated Balance Saved)'), ('EXPIRED_ARCHIVE', 'Expired (Read-Only Data Archive)')], default='ACTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='businessmodule',
            name='icon_class',
            field=models.CharField(default='fa-boxes-stacked', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantappsubscription',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.businessmodule'),
        ),
        migrations.AlterField(
            model_name='tenantappsubscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='KosiskoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='app_icons/')),
                ('has_demo', models.BooleanField(default=True)),
                ('demo_sandbox_url', models.URLField(blank=True, help_text='सुरक्षित डमी डेमो रूम का लिंक', null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_system_app', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='marketplace.appcategory')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tenantappsubscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tenantappsubscription',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.kosiskoapp'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantappsubscription',
            unique_together={('tenant', 'app')},
        ),
        migrations.RemoveField(
            model_name='tenantappsubscription',
            name='is_active',
        ),
    ]
