# Generated by Django 6.1 on 2026-09-21 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_platform', '0008_tenant_allowed_ips_tenant_api_key_and_more'),
        ('marketplace', '0002_appcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantappsubscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_subscriptions', to='core_platform.tenant'),
        ),
    ]
