# Generated by Django 6.0.7 on 2026-08-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_platform', '0005_userprofile_role_userprofile_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('has_whitelabel_subscription', models.BooleanField(default=False)),
                ('custom_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_logo', models.ImageField(blank=True, null=True, upload_to='whitelabel_logos/')),
            ],
        ),
    ]
