# Generated by Django 6.0.7 on 2026-08-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_platform', '0006_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='whitelabel_favicons/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_logo',
            field=models.ImageField(blank=True, null=True, upload_to='whitelabel_logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='has_whitelabel_subscription',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='magic_login_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agenticaiactionlog',
            name='action_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agenticaiactionlog',
            name='target_module',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agenticaiactionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='appstoremodule',
            name='category',
            field=models.CharField(db_index=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='appstoremodule',
            name='module_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='flat_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='valid_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantcustompricing',
            name='module_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='is_unlocked',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gst_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Owner / Admin'), ('manager', 'Manager'), ('staff_operator', 'Staff / Operator'), ('team_member', 'Team Member'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agenticaiactionlog',
            index=models.Index(fields=['tenant', 'timestamp'], name='core_platfo_tenant__1b96b5_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['tenant', 'is_unlocked'], name='core_platfo_tenant__af712d_idx'),
        ),
    ]
