# Generated by Django 6.1 on 2026-09-21 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_platform', '0007_delete_organization_tenant_custom_brand_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allowed_ips',
            field=models.TextField(blank=True, help_text='सुरक्षा के लिए आईपी व्हाइटलिस्टिंग (कॉमा सेपरेटेड)', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='api_key',
            field=models.CharField(blank=True, help_text='टेनेंट-वाइज यूनिक एपीआई की', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, help_text='कस्टम डोमेन (उदा. portal.clientdomain.com)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_custom_domain_verified',
            field=models.BooleanField(default=False, help_text='DNS CNAME रिकॉर्ड वेरीफाई हुआ या नहीं'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, help_text='जब तक पेमेंट सफल नहीं होगी, यह False रहेगा'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='पेमेंट फेल होने पर ऑटो-सस्पेंशन'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_users',
            field=models.IntegerField(default=5, help_text='इस टेनेंट के लिए अधिकतम स्टाफ/यूजर लिमिट'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#4F46E5', help_text='प्राइमरी थीम कलर कोड', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sidebar_bg_color',
            field=models.CharField(default='#1E293B', help_text='डैशबोर्ड साइडबार बैकग्राउंड कलर', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sidebar_position',
            field=models.CharField(choices=[('left', 'Left Sidebar'), ('right', 'Right Sidebar'), ('top', 'Top Navbar')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ssl_status',
            field=models.CharField(default='pending', help_text='SSL सर्टिफिकेट स्टेटस (pending/active)', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='storage_limit_gb',
            field=models.FloatField(default=10.0, help_text='डेटा और फाइल स्टोरेज लिमिट (GB में)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text='अगला रिन्यूअल या एक्सपायरी डेट', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='फ्री ट्रायल समाप्ति तिथि', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='कंपनी / बिजनेस का नाम', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(db_index=True, help_text='यूनिक सबडोमेन slug (उदा. tata)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_subscriptions', to='core_platform.tenant'),
        ),
    ]
