# Generated by Django 6.1 on 2026-09-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_platform', '0008_tenant_allowed_ips_tenant_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True),
        ),
    ]
