# Generated by Django 6.0.7 on 2026-08-03 04:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('TECHNICIAN', 'Technician')], default='CUSTOMER', max_length=20)),
                ('referral_code', models.CharField(default=uuid.uuid4, max_length=30, unique=True)),
                ('total_successful_refers', models.IntegerField(default=0)),
                ('reward_wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_referral_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'Monthly Subscription'), ('YEARLY', 'Yearly Plan'), ('PER_DAY', 'Per-Day Micro Billing (e.g. ₹9.99/day)'), ('CUSTOM', 'Custom Duration Plan')], default='MONTHLY', max_length=20)),
                ('duration_days', models.IntegerField(default=30, help_text='प्लान की कुल अवधि (दिनों में)')),
                ('price_per_day', models.DecimalField(decimal_places=2, default=9.99, max_digits=10)),
                ('total_plan_price', models.DecimalField(decimal_places=2, default=499.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_plans', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SmartIoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text='e.g. Device-INDORE-001', max_length=100)),
                ('model_number', models.CharField(default='Smart-IoT-V2', max_length=100)),
                ('tuya_device_id', models.CharField(help_text='Tuya IoT Smart Relay ID', max_length=128, unique=True)),
                ('installation_date', models.DateField(default=django.utils.timezone.now)),
                ('installation_latitude', models.FloatField(blank=True, null=True)),
                ('installation_longitude', models.FloatField(blank=True, null=True)),
                ('relay_status', models.BooleanField(default=True, help_text='True = Power ON, False = Cutoff')),
                ('input_quality_tds', models.IntegerField(default=350, help_text='Raw Water TDS / Voltage')),
                ('output_quality_tds', models.IntegerField(default=45, help_text='Filtered Output TDS / Output Status')),
                ('primary_filter_life', models.IntegerField(default=100)),
                ('secondary_filter_life', models.IntegerField(default=100)),
                ('core_membrane_life', models.IntegerField(default=100)),
                ('total_output_units', models.FloatField(default=0.0, help_text='Total Liters/Units Consumed')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Operational'), ('CUTOFF', 'Cutoff (Relay OFF - Recharge Due)'), ('MAINTENANCE', 'Maintenance Required'), ('OFFLINE', 'Device Offline / Wi-Fi Disconnected')], default='ACTIVE', max_length=20)),
                ('next_due_date', models.DateField()),
                ('prorated_credit_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_ping_at', models.DateTimeField(auto_now=True)),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot_smart_rental.rentalplan')),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_devices', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_devices', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='technicians/photos/')),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_on_leave', models.BooleanField(default=False, help_text='छुट्टी पर होने पर नज़दीकी टेक्नीशियन को ऑटो-असाइन होगा')),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('per_job_incentive', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('referral_commission_rate', models.DecimalField(decimal_places=2, default=200.0, help_text='प्रति सफल रेफरल बोनस', max_digits=10)),
                ('average_rating', models.FloatField(default=5.0)),
                ('assigned_devices', models.ManyToManyField(blank=True, related_name='assigned_technicians', to='iot_smart_rental.smartiotdevice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Service Request Raised'), ('ASSIGNED', 'Technician Assigned'), ('IN_PROGRESS', 'Technician En Route'), ('COMPLETED', 'Job Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_rating', models.IntegerField(blank=True, help_text='1 to 5 Star Rating', null=True)),
                ('customer_feedback', models.TextField(blank=True, null=True)),
                ('incentive_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tickets', to='tenants.tenant')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tickets', to='iot_smart_rental.smartiotdevice')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='iot_smart_rental.technicianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NewDeviceOnboardingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=15)),
                ('installation_address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=1999.0, max_digits=10)),
                ('payment_transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PAYMENT_DONE', 'Payment Completed'), ('READY_TO_DISPATCH', 'Ready to Dispatch from Warehouse'), ('OUT_FOR_DELIVERY', 'Out for Delivery (Technician En Route)'), ('INSTALLED', 'Successfully Installed & Active')], default='PAYMENT_DONE', max_length=30)),
                ('supervisor_manager_name', models.CharField(default='Central Customer Support', max_length=100)),
                ('supervisor_manager_phone', models.CharField(default='+91 9876543210', max_length=15)),
                ('target_installation_deadline', models.DateTimeField(help_text='24 to 48 hours SLA Timer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot_smart_rental.referralaccount')),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot_smart_rental.technicianprofile')),
            ],
        ),
    ]
