# Generated by Django 6.0.7 on 2026-08-05 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_smart_rental', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('ONBOARDING', 'New Machine Booking Deposit'), ('RECHARGE', 'Monthly Subscription Recharge')], default='RECHARGE', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=10)),
                ('payment_mode', models.CharField(default='UPI / Online', max_length=30)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot_smart_rental.smartiotdevice')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
