# Generated by Django 6.1 on 2026-09-21 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_platform', '0008_tenant_allowed_ips_tenant_api_key_and_more'),
        ('iot_smart_rental', '0002_paymentinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdeviceonboardinglead',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_platform.tenant'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_platform.tenant'),
        ),
        migrations.AlterField(
            model_name='referralaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core_platform.tenant'),
        ),
        migrations.AlterField(
            model_name='rentalplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_plans', to='core_platform.tenant'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tickets', to='core_platform.tenant'),
        ),
        migrations.AlterField(
            model_name='smartiotdevice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_devices', to='core_platform.tenant'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='core_platform.tenant'),
        ),
    ]
